name: td3

agent_name: ${now:%Y%m%d}_td3_gnn  # Agent name for training or evaluation (default: today's date + '_sac_gnn')

cplexpath: "/opt/opl/bin/x86-64_linux/"  # Defines directory of the CPLEX installation

directory: "saved_files"  # Defines directory where to save files

max_episodes: 120  # Number of episodes to train agent (default: 16k)

no_cuda: true  # Disables CUDA training

batch_size: 100  # Defines batch size

checkpoint_path: "TD3"  # Path where to save model checkpoints
  
rew_scale: 0.001  # Defines reward scale

hidden_size: 256  # Defines hidden units in the MLP layers

input_size: 13 # Number of node features

test_episodes: 10 # Number of episodes to test agent
